fs.CountError: Modify behavior to use correct Stats instead of GlobalStats
fs.CountError was called when an error is encountered.
The method was calling GlobalStats().Error(err) which incremented the
error at the global stats level.
This led to calls to core/stats with group= filter returning an error
count of 0 even if errors actually occured.